version: "1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - elastic
  springApp:
    image: co.empathy.academy/search
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - elastic
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
