version: "1"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    networks:
      - elastic
  springApp:
    image: co.empathy.academy/search
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
